/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_grumpycat_pcaplib_port_PortService */

#ifndef _Included_com_grumpycat_pcaplib_port_PortService
#define _Included_com_grumpycat_pcaplib_port_PortService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_grumpycat_pcaplib_port_PortService_MSG_TYPE_QUERY
#define com_grumpycat_pcaplib_port_PortService_MSG_TYPE_QUERY 20L

JNIEXPORT jint JNICALL
Java_com_grumpycat_pcaplib_port_PortService_parseUidByPort(JNIEnv *env, jclass type_, jint port,
                                                           jint type);



#ifdef __cplusplus
}
#endif
#endif
